version: '3.5'

services:
  iface_db:
      image: postgres:16-alpine
      hostname: iface_pg
      ports:
        - "5433:5432"
      environment:
        - "POSTGRES_PASSWORD=postgres"
        - "POSTGRES_USER=root"
        - "POSTGRES_DB=iface_db"
        - "PGDATA=/var/lib/postgresql/data/pgdata"
      volumes:
      - "iface_db_volume:/var/lib/postgresql/data/pgdata"

volumes:
  iface_db_volume:
